export var car_database = [
    {
      "objectId": "ZRgPP9dBMm",
      "url": "https://images.dealer.com/ddc/vehicles/2023/Audi/Q3/SUV/trim_40_Komfort_032f53/color/Navarra%20Blue%20Metallic-2D2D-23,32,52-640-en_CA.jpg",
      "Year": 2020,
      "Make": "Audi",
      "Model": "Q3",
      "Category": "SUV",
      "Mileage": "254190",
      "Color": "Blue",
      "Price": "$7,500",
      "Seats": "4",
      "Bags": {"Large": "3", "Small": "3"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people and/or heavy luggages",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "cptB1C1NSL",
      "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCZcNbVfa2xpbAzH-wIAoqcepQrO4TkJKbpQ&usqp=CAU",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Malibu",
      "Category": "Sedan",
      "Mileage": "254190",
      "Color": "Red",
      "Price": "$5,500",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "1"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "ElhqsRZDnP",
      "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrp4Zl8F-CzWq09EGIlduMU_L4Q7h59oC1oQ&usqp=CAU",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "Escalade ESV",
      "Category": "SUV",
      "Mileage": "254190",
      "Color": "Gray",
      "Price": "$20,750",
      "Seats": "6",
      "Bags": {"Large": "5", "Small": "3"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people and/or heavy luggages",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "LUzyWMYJpW",
      "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8r8mVnpJAHNSxw9kNHRTW6QidSwb2NBdWhw&usqp=CAU",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Corvette",
      "Category": "Coupe, Convertible",
      "Mileage": "254190",
      "Color": "White",
      "Price": "$6,100",
      "Seats": "2",
      "Bags": {"Large": "1", "Small": "1"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "rDkHakOBKP",
      "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPFFOMu6gR6BNALBcPvcrlx4Jn22k5RHrp1A&usqp=CAU",
      "Year": 2020,
      "Make": "Acura",
      "Model": "RLX",
      "Category": "Sedan",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "1JARpJ2AUB",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Silverado 2500 HD Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "7G1VT2pSNO",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "BMW",
      "Model": "3 Series",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "4q7L9FAU2S",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chrysler",
      "Model": "Pacifica",
      "Category": "Van/Minivan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "jpOC5zs3jx",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Colorado Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "96llWfTOAe",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "BMW",
      "Model": "X3",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "5OEvsF1R9k",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Acura",
      "Model": "TLX",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "LNq3duGh9z",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Silverado 3500 HD Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "FThs77Cddn",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "BMW",
      "Model": "7 Series",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "t9eGFMIk7E",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Fusion",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "cWQjuYWwc2",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Buick",
      "Model": "Envision",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "2lYY81jKzR",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Audi",
      "Model": "SQ5",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "qGDd5H3yYd",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Audi",
      "Model": "R8",
      "Category": "Coupe, Convertible",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "ALbinxfzM1",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Traverse",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "9eRGwnViia",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Acura",
      "Model": "MDX",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "kAgBF7aSaO",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "INFINITI",
      "Model": "QX80",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "ygsDiv3hRm",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Buick",
      "Model": "Encore",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "92pfQo6pA4",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "GMC",
      "Model": "Sierra 2500 HD Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "VfXndYon3e",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Insight",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "grl6dVnzM9",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "XT6",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "QrYfmqcnAR",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "XT5",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "hSaQDQkkE0",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "XT4",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "rSQyj88Pwe",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Buick",
      "Model": "Enclave",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "kkcmfophql",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Audi",
      "Model": "Q5",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "V1F5kE5svr",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Santa Fe",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "bW6jRQ3h2S",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Ford",
      "Model": "EcoSport",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "6YcNNwgY0C",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Escape",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "dxs3ayh6Yl",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Mustang",
      "Category": "Coupe, Convertible",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "yZUeGC1bOn",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Sonata",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "JyMpQJbCvy",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Ford",
      "Model": "Edge",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "VT4rtTsGBj",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Camaro",
      "Category": "Convertible",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "vRQFNeVlsa",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Hyundai",
      "Model": "Kona Electric",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "OHHuEGKsUC",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Equinox",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "vu2lCeXKzk",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "GMC",
      "Model": "Sierra 3500 HD Crew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "rg8LbH5ixZ",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Jeep",
      "Model": "Gladiator",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "ifEdBTIVDH",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "BMW",
      "Model": "X7",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "4J2BvKonKq",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "CT6-V",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "PlNwrAm6eM",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Audi",
      "Model": "A7",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "VK6hmDAvqP",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Blazer",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "vidGAd8cIJ",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Ford",
      "Model": "F150 SuperCrew Cab",
      "Category": "Pickup",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "NHWgNGSFB7",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chevrolet",
      "Model": "Suburban",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "MTvnyKqtYJ",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Civic",
      "Category": "Hatchback, Sedan, Coupe",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "wTXL9Ze5eF",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Jeep",
      "Model": "Compass",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.666Z",
      "updatedAt": "2020-01-27T20:44:17.666Z"
    },
    {
      "objectId": "SCG7WEYdG1",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Cadillac",
      "Model": "Escalade",
      "Category": "SUV",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "cKnegrw5AO",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Chrysler",
      "Model": "Voyager",
      "Category": "Van/Minivan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    },
    {
      "objectId": "smKxD5m9KI",
      "Mileage": "254190",
      "Color": "Black",
      "Price": "$4,450",
      "Seats": "4",
      "Bags": {"Large": "2", "Small": "2"},
      "Transmission": "Automatic",
      "Recommendation": "Recommended for transporting people",
      "url": "",
      "Year": 2020,
      "Make": "Honda",
      "Model": "Accord Hybrid",
      "Category": "Sedan",
      "createdAt": "2020-01-27T20:44:17.665Z",
      "updatedAt": "2020-01-27T20:44:17.665Z"
    }
  ];


export var repairs_database = [
  {
    "title": "Axle & Driveshaft Repair",
    "url": "https://media.istockphoto.com/id/1395862805/vector/axle.jpg?s=612x612&w=0&k=20&c=2zc-TYSh8uI3exHjmZlusLa9ArOImHOu0WV86KzJCbs=",
    "content": "When it comes to keeping your vehicle running smoothly, proper maintenance of crucial components like axles and driveshafts is paramount. Axles and driveshafts play a vital role in transmitting power from the engine to the wheels, ensuring optimal performance and safe driving",
    "Price": {"home": "$15", "workshop": "$10"}

  },
  {
    "title": "Belts & Hoses",
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT345BKCrNBy9iEx6B0eGNLL8CuK5IzzI-LHg&usqp=CAU",
    "Price": {"home": "$15", "workshop": "$10"},
    "content": "Maintaining the health of your vehicle's belts and hoses is essential to ensure a smooth and trouble-free driving experience. Belts and hoses play a critical role in the proper functioning of your engine, cooling system, and various components."
  },
  {
    "title": "Brake Repair",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRq8n2S9fsHZQ3kn2gp2I8N15nf7nxBwz3KGw&usqp=CAU",
    "content": "Your safety on the road is our top priority, and that's why we offer comprehensive brake repair services to keep your vehicle's braking system in optimal condition. A well-functioning brake system is crucial for your vehicle's performance and your peace of mind."
  },
  {
    "title": "Cooling System Repairs",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSu1dz-HV5g-j1o4RQEwNG0iPoVsYyjkypFQg&usqp=CAU",
    "content": "Keeping your engine operating at the right temperature is essential for optimal performance and longevity. Your vehicle's cooling system is responsible for preventing overheating and maintaining the right operating temperature. "
  },
  {
    "title": "Electrical and Electronic Systems",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSe0dTxP3ujr1xo70sF18iaDSz_JZt1v1vMqg&usqp=CAU",
    "content": "In today's modern vehicles, electrical and electronic systems play a pivotal role in powering essential functions and enhancing driving comfort.From power windows and door locks to advanced infotainment and navigation systems, our expert technicians are equipped to diagnose and address a wide range of electrical and electronic issues."
  },
  {
    "title": "Engine Diagnostics and Performance",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFjCjCBXIPJ-P6LYnwY6EmPVwFkoGuyIARhg&usqp=CAU",
    "content": "Our expert technicians are well-versed in the intricacies of modern engine systems. Using advanced diagnostic tools, we can pinpoint issues affecting your engine's performance, whether it's reduced power, rough idling, or increased emissions. We leave no stone unturned in diagnosing and addressing these problems."
  },
  {
    "title": "Exhaust System Repair",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqhkzwD6l9h0dLkXpUkwcg2Cw6Y5Fnai0IMw&usqp=CAU",
    "content": "Your vehicle's exhaust system is not only responsible for reducing noise, but it also plays a critical role in minimizing emissions and maintaining engine performance. At [Your Auto Exhaust Repair], we specialize in comprehensive exhaust system repairs to keep your car running smoothly and efficiently."
  },
  {
    "title": "Four Wheel Repair",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsI_OAlgsgIZUj6fP-KPRlcUk1CsHMWPIOtw&usqp=CAU",
    "content": "Ensuring that all four wheels of your vehicle are in optimal condition is crucial for a smooth and safe driving experience. At [Your Four Wheel Repair Experts], we specialize in comprehensive four-wheel repair services to keep your vehicle balanced, aligned, and performing at its best."
  },
  {
    "title": "Lube, Oil & Filter Change",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeBU1K0waEuL1cxh21G2DP1xG2bTJDzxERXDshG5Rf9sqmOjLJYj5ZnYXxBQfgFWWEqFI&usqp=CAU",
    "content": "At [Your Auto Care Center], we're all about keeping your vehicle's engine in top shape. Our Cars Lube, Oil & Filter Change service is designed to ensure your car runs smoothly, efficiently, and reliably."
  },
  {
    "title": "Preventive Maintenance",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgVFC6D1oFHU-ilh-pTcLqMfSQmo5Ft2oXlA&usqp=CAU",
    "content": "At [Your Auto Repair Shop], we understand that a well-maintained car is a reliable car. Our Preventive Maintenance service is designed to keep your vehicle performing at its best, minimizing the chances of unexpected breakdowns and costly repairs."
  },
  {
    "title": "Roadside Assistance",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeiKktfS8Jx1OTEV71pj_H7T5ww5LlIDKXyg&usqp=CAU",
    "content": "At RoadGuard Assist, we understand that your safety and convenience are paramount. Our dedicated team of trained professionals is just a phone call away, 24/7, ready to provide you with the assistance you need. Whether you're stranded in the middle of nowhere or right in the heart of the city, we've got you covered."
  },
  {
    "title": "Starting, Charging & Batteries",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPp8PMoFGa6yoMl_Tn1TGRXE9RTq1xsblbwQ&usqp=CAU",
    "content": "Your car's ability to start up and run smoothly depends on a healthy heart: its battery and charging system. At PowerPulse Auto Care, we understand the importance of a reliable starting mechanism, and we're here to ensure your vehicle's heart beats strong."
  },
  {
    "title": "Steering and Suspension System",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQuLPYr3B7bIOXE1uCb1ASRtCKY5PyC7F5pA&usqp=CAU",
    "content": "Your car's steering and suspension systems play a crucial role in maintaining control, stability, and overall ride quality.A well-functioning suspension system is integral to a smooth and comfortable ride. Our skilled professionals meticulously examine each element of your suspension system, including shocks, struts, springs, and bushings. We identify any signs of damage, leaks, or decreased performance. If you're experiencing a bumpy ride, uneven tire wear, or a dipping nose during braking, our team will address the problem effectively."
  },
  {
    "title": "Tire Pressure Monitoring System",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuZWVweahHVhP7BBu6cM0eQMFiNQq_fzGitQ&usqp=CAU",
    "content": "At [Your Auto Care Center], we understand the critical role that properly inflated tires play in ensuring your safety and enhancing your vehicle's performance. Our dedicated team of technicians is here to provide top-notch Tire Pressure Monitoring System (TPMS) services that keep your tires in the ideal condition for a smooth and secure ride."
  },
  {
    "title": "Tire Services",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8lJGO5KTpjClWtqOhtGyfVR5Cxhp13GS7MQ&usqp=CAU",
    "content": "Regular tire rotation is essential to promote even tire wear and extend tire life. Our technicians follow manufacturer recommendations to rotate your tires systematically, ensuring that each tire experiences different wear patterns. This service maximizes tire longevity and contributes to consistent handling and performance across all four wheels."
  },
  {
    "title": "Transmission Repair",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjp5y5xaR-bJSmQ75wviTybSmkIGNuSYfXBA&usqp=CAU",
    "content": "At [Your Auto Repair Shop], we pride ourselves on delivering transmission repair services that stand out for their quality and reliability. Whether you drive a manual or automatic transmission vehicle, our team has the expertise to diagnose, repair, and maintain your transmission system. Schedule an appointment today and experience the difference of a well-maintained and smoothly operating transmission."
  },
  {
    "title": "Vehicle Inspection",
    "Price": {"home": "$15", "workshop": "$10"},
    "url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTExOInZW4824y6McxNge_mcMLbgzpXLTJxWg&usqp=CAU",
    "content": "Our vehicle inspection process begins with a comprehensive visual assessment of your vehicle's exterior, interior, and undercarriage. Our technicians meticulously examine the body, paint, lights, windows, mirrors, and interior components for any signs of wear, damage, or issues that might affect your vehicle's aesthetics and functionality."
  }
]

export var faq =  [
  {"faq": "Question 1: Sales", "answer": "Answer 1: Sales", "category": "Sales"},
  {"faq": "Question 2: Sales", "answer": "Answer 2: Sales", "category": "Sales"},
  {"faq": "Question 3: Rentals", "answer": "Answer 3: Rentals", "category": "Rentals"},
  {"faq": "Question 4: Rentals", "answer": "Answer 4: Rentals", "category": "Rentals"},
  {"faq": "Question 5: Sales", "answer": "Answer 5: Sales", "category": "Sales"},
  {"faq": "Question 6: Repairs", "answer": "Answer 6: Repairs", "category": "Repairs"},
  {"faq": "Question 7: Repairs", "answer": "Answer 7: Repairs", "category": "Repairs"},
  {"faq": "Question 8: Repairs", "answer": "Answer 8: Repairs", "category": "Repairs"},
  {"faq": "Question 9: Rentals", "answer": "Answer 9: Rentals", "category": "Rentals"},
  {"faq": "Question 10: Sales", "answer": "Answer 10: Sales", "category": "Sales"}
];